title: Snow-Leopard-DVD-Creator
description: Script to create a bootable Snow Leopard DVD and installing Chameleon
github: 
  repository_url: https://github.com/chris1111/Snow-Leopard-DVD-Creator
remote_theme: chris1111/cayman-dark

